# tests/test_catalog.py
import hashlib
import pytest
import respx
import httpx
from kabooz import QobuzClient, Quality
from kabooz.exceptions import NoAuthError, NotStreamableError


BASE = "https://www.qobuz.com/api.json/0.2"


def authenticated_client() -> QobuzClient:
    """
    Helper that returns a client with a session already set.
    We use login(token=...) here because we've already tested the
    password login path thoroughly — no need to mock the login
    endpoint in every catalog test.
    """
    client = QobuzClient.from_credentials(app_id="123", app_secret="abc")
    client.login(token="TEST_TOKEN", user_id="99999")
    return client


# ── get_track ──────────────────────────────────────────────────────────────

@respx.mock
def test_get_track_returns_data():
    """get_track() should return the parsed JSON body from the API."""
    respx.get(f"{BASE}/track/get").mock(
        return_value=httpx.Response(200, json={
            "id": 12345,
            "title": "One More Time",
            "duration": 320,
        })
    )
    client = authenticated_client()
    track = client.get_track("12345")
    assert track["id"] == 12345
    assert track["title"] == "One More Time"


@respx.mock
def test_get_track_injects_auth_token():
    """
    Every authenticated request should include the user_auth_token
    in its query parameters. This is how Qobuz knows who is asking.
    """
    captured = {}

    def capture(request):
        captured["url"] = str(request.url)
        return httpx.Response(200, json={"id": 12345, "title": "Test"})

    respx.get(f"{BASE}/track/get").mock(side_effect=capture)

    client = authenticated_client()
    client.get_track("12345")

    assert "TEST_TOKEN" in captured["url"]


@respx.mock
def test_get_track_not_found_raises():
    """A 404 from the API should raise NotFoundError."""
    from kabooz.exceptions import NotFoundError
    respx.get(f"{BASE}/track/get").mock(
        return_value=httpx.Response(404, json={"message": "Track not found"})
    )
    client = authenticated_client()
    with pytest.raises(NotFoundError):
        client.get_track("99999999")


# ── get_album ──────────────────────────────────────────────────────────────

@respx.mock
def test_get_album_returns_data():
    respx.get(f"{BASE}/album/get").mock(
        return_value=httpx.Response(200, json={
            "id": "abc123",
            "title": "Discovery",
            "tracks_count": 14,
        })
    )
    client = authenticated_client()
    album = client.get_album("abc123")
    assert album["title"] == "Discovery"
    assert album["tracks_count"] == 14


# ── search ─────────────────────────────────────────────────────────────────

@respx.mock
def test_search_returns_results():
    respx.get(f"{BASE}/catalog/search").mock(
        return_value=httpx.Response(200, json={
            "tracks": {"items": [{"id": 1, "title": "Test Track"}]},
            "query": "daft punk",
        })
    )
    client = authenticated_client()
    results = client.search("daft punk", type="tracks")
    assert results["query"] == "daft punk"
    assert len(results["tracks"]["items"]) == 1


# ── get_track_url ──────────────────────────────────────────────────────────

@respx.mock
def test_get_track_url_returns_url():
    """get_track_url() should return a dict containing a 'url' key."""
    respx.get(f"{BASE}/track/getFileUrl").mock(
        return_value=httpx.Response(200, json={
            "url": "https://cdn.qobuz.com/some/signed/url.flac",
            "format_id": 27,
            "bit_depth": 24,
            "sampling_rate": 96.0,
            "mime_type": "audio/flac",
        })
    )
    client = authenticated_client()
    result = client.get_track_url("12345", quality=Quality.HI_RES)
    assert "url" in result
    assert result["bit_depth"] == 24


@respx.mock
def test_get_track_url_includes_signature():
    """
    The request to getFileUrl must include request_ts and request_sig.
    Without these the API will reject it — they prove the request was
    generated by a legitimate app that knows the App Secret.
    """
    captured = {}

    def capture(request):
        captured["url"] = str(request.url)
        return httpx.Response(200, json={
            "url": "https://cdn.qobuz.com/file.flac"
        })

    respx.get(f"{BASE}/track/getFileUrl").mock(side_effect=capture)

    client = authenticated_client()
    client.get_track_url("12345")

    assert "request_ts" in captured["url"]
    assert "request_sig" in captured["url"]


@respx.mock
def test_get_track_url_not_streamable_raises():
    """
    Qobuz sometimes returns HTTP 200 with no 'url' in the body instead
    of a proper error code. We should raise NotStreamableError in this
    case rather than returning an unusable dict to the caller.
    """
    respx.get(f"{BASE}/track/getFileUrl").mock(
        return_value=httpx.Response(200, json={
            "message": "Restricted by label"
        })
    )
    client = authenticated_client()
    with pytest.raises(NotStreamableError):
        client.get_track_url("12345")


def test_get_track_url_without_auth_raises():
    """get_track_url() without a session should raise NoAuthError before
    any network call is made."""
    client = QobuzClient.from_credentials(app_id="123", app_secret="abc")
    with pytest.raises(NoAuthError):
        client.get_track_url("12345")


@respx.mock
def test_rate_limit_raises():
    """A 429 response from any endpoint should raise RateLimitError."""
    from kabooz.exceptions import RateLimitError
    respx.get(f"{BASE}/track/get").mock(
        return_value=httpx.Response(429, json={"message": "Too many requests"})
    )
    client = authenticated_client()
    with pytest.raises(RateLimitError):
        client.get_track("12345")
